// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: proto/rangeservice/range.proto

package rangeservice

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RangeService_Execute_FullMethodName = "/rangeservice.RangeService/Execute"
)

// RangeServiceClient is the client API for RangeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RangeServiceClient interface {
	Execute(ctx context.Context, in *RangeRequest, opts ...grpc.CallOption) (*RangeResponse, error)
}

type rangeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRangeServiceClient(cc grpc.ClientConnInterface) RangeServiceClient {
	return &rangeServiceClient{cc}
}

func (c *rangeServiceClient) Execute(ctx context.Context, in *RangeRequest, opts ...grpc.CallOption) (*RangeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RangeResponse)
	err := c.cc.Invoke(ctx, RangeService_Execute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RangeServiceServer is the server API for RangeService service.
// All implementations must embed UnimplementedRangeServiceServer
// for forward compatibility.
type RangeServiceServer interface {
	Execute(context.Context, *RangeRequest) (*RangeResponse, error)
	mustEmbedUnimplementedRangeServiceServer()
}

// UnimplementedRangeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRangeServiceServer struct{}

func (UnimplementedRangeServiceServer) Execute(context.Context, *RangeRequest) (*RangeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedRangeServiceServer) mustEmbedUnimplementedRangeServiceServer() {}
func (UnimplementedRangeServiceServer) testEmbeddedByValue()                      {}

// UnsafeRangeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RangeServiceServer will
// result in compilation errors.
type UnsafeRangeServiceServer interface {
	mustEmbedUnimplementedRangeServiceServer()
}

func RegisterRangeServiceServer(s grpc.ServiceRegistrar, srv RangeServiceServer) {
	// If the following call panics, it indicates UnimplementedRangeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RangeService_ServiceDesc, srv)
}

func _RangeService_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RangeServiceServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RangeService_Execute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RangeServiceServer).Execute(ctx, req.(*RangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RangeService_ServiceDesc is the grpc.ServiceDesc for RangeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RangeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rangeservice.RangeService",
	HandlerType: (*RangeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Execute",
			Handler:    _RangeService_Execute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/rangeservice/range.proto",
}
