// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/rangeservice/range.proto

package rangeservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RangeOp int32

const (
	RangeOp_SCAN   RangeOp = 0
	RangeOp_INSERT RangeOp = 1
	RangeOp_UPDATE RangeOp = 2
	RangeOp_DELETE RangeOp = 3
)

// Enum value maps for RangeOp.
var (
	RangeOp_name = map[int32]string{
		0: "SCAN",
		1: "INSERT",
		2: "UPDATE",
		3: "DELETE",
	}
	RangeOp_value = map[string]int32{
		"SCAN":   0,
		"INSERT": 1,
		"UPDATE": 2,
		"DELETE": 3,
	}
)

func (x RangeOp) Enum() *RangeOp {
	p := new(RangeOp)
	*p = x
	return p
}

func (x RangeOp) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RangeOp) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_rangeservice_range_proto_enumTypes[0].Descriptor()
}

func (RangeOp) Type() protoreflect.EnumType {
	return &file_proto_rangeservice_range_proto_enumTypes[0]
}

func (x RangeOp) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RangeOp.Descriptor instead.
func (RangeOp) EnumDescriptor() ([]byte, []int) {
	return file_proto_rangeservice_range_proto_rawDescGZIP(), []int{0}
}

// Field mirrors btree.Field: a tag plus a typed value.
type FieldValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*FieldValue_IntVal
	//	*FieldValue_StrVal
	Value         isFieldValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldValue) Reset() {
	*x = FieldValue{}
	mi := &file_proto_rangeservice_range_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldValue) ProtoMessage() {}

func (x *FieldValue) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rangeservice_range_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldValue.ProtoReflect.Descriptor instead.
func (*FieldValue) Descriptor() ([]byte, []int) {
	return file_proto_rangeservice_range_proto_rawDescGZIP(), []int{0}
}

func (x *FieldValue) GetValue() isFieldValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *FieldValue) GetIntVal() int64 {
	if x != nil {
		if x, ok := x.Value.(*FieldValue_IntVal); ok {
			return x.IntVal
		}
	}
	return 0
}

func (x *FieldValue) GetStrVal() string {
	if x != nil {
		if x, ok := x.Value.(*FieldValue_StrVal); ok {
			return x.StrVal
		}
	}
	return ""
}

type isFieldValue_Value interface {
	isFieldValue_Value()
}

type FieldValue_IntVal struct {
	IntVal int64 `protobuf:"varint,1,opt,name=int_val,json=intVal,proto3,oneof"`
}

type FieldValue_StrVal struct {
	StrVal string `protobuf:"bytes,2,opt,name=str_val,json=strVal,proto3,oneof"`
}

func (*FieldValue_IntVal) isFieldValue_Value() {}

func (*FieldValue_StrVal) isFieldValue_Value() {}

type Field struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           uint32                 `protobuf:"varint,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Value         *FieldValue            `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Field) Reset() {
	*x = Field{}
	mi := &file_proto_rangeservice_range_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Field) ProtoMessage() {}

func (x *Field) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rangeservice_range_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Field.ProtoReflect.Descriptor instead.
func (*Field) Descriptor() ([]byte, []int) {
	return file_proto_rangeservice_range_proto_rawDescGZIP(), []int{1}
}

func (x *Field) GetTag() uint32 {
	if x != nil {
		return x.Tag
	}
	return 0
}

func (x *Field) GetValue() *FieldValue {
	if x != nil {
		return x.Value
	}
	return nil
}

// Expression encodes a sqllayer WHERE tree.
type ComparisonExpr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Column        string                 `protobuf:"bytes,1,opt,name=column,proto3" json:"column,omitempty"`
	Operator      string                 `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator,omitempty"`
	LiteralValue  string                 `protobuf:"bytes,3,opt,name=literal_value,json=literalValue,proto3" json:"literal_value,omitempty"`
	LiteralType   int32                  `protobuf:"varint,4,opt,name=literal_type,json=literalType,proto3" json:"literal_type,omitempty"` // sqllayer.TokenType
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComparisonExpr) Reset() {
	*x = ComparisonExpr{}
	mi := &file_proto_rangeservice_range_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComparisonExpr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComparisonExpr) ProtoMessage() {}

func (x *ComparisonExpr) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rangeservice_range_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComparisonExpr.ProtoReflect.Descriptor instead.
func (*ComparisonExpr) Descriptor() ([]byte, []int) {
	return file_proto_rangeservice_range_proto_rawDescGZIP(), []int{2}
}

func (x *ComparisonExpr) GetColumn() string {
	if x != nil {
		return x.Column
	}
	return ""
}

func (x *ComparisonExpr) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *ComparisonExpr) GetLiteralValue() string {
	if x != nil {
		return x.LiteralValue
	}
	return ""
}

func (x *ComparisonExpr) GetLiteralType() int32 {
	if x != nil {
		return x.LiteralType
	}
	return 0
}

type LogicalExpr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operator      string                 `protobuf:"bytes,1,opt,name=operator,proto3" json:"operator,omitempty"`
	Left          *Expression            `protobuf:"bytes,2,opt,name=left,proto3" json:"left,omitempty"`
	Right         *Expression            `protobuf:"bytes,3,opt,name=right,proto3" json:"right,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogicalExpr) Reset() {
	*x = LogicalExpr{}
	mi := &file_proto_rangeservice_range_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogicalExpr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogicalExpr) ProtoMessage() {}

func (x *LogicalExpr) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rangeservice_range_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogicalExpr.ProtoReflect.Descriptor instead.
func (*LogicalExpr) Descriptor() ([]byte, []int) {
	return file_proto_rangeservice_range_proto_rawDescGZIP(), []int{3}
}

func (x *LogicalExpr) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *LogicalExpr) GetLeft() *Expression {
	if x != nil {
		return x.Left
	}
	return nil
}

func (x *LogicalExpr) GetRight() *Expression {
	if x != nil {
		return x.Right
	}
	return nil
}

type Expression struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Expr:
	//
	//	*Expression_Comparison
	//	*Expression_Logical
	Expr          isExpression_Expr `protobuf_oneof:"expr"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Expression) Reset() {
	*x = Expression{}
	mi := &file_proto_rangeservice_range_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Expression) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Expression) ProtoMessage() {}

func (x *Expression) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rangeservice_range_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Expression.ProtoReflect.Descriptor instead.
func (*Expression) Descriptor() ([]byte, []int) {
	return file_proto_rangeservice_range_proto_rawDescGZIP(), []int{4}
}

func (x *Expression) GetExpr() isExpression_Expr {
	if x != nil {
		return x.Expr
	}
	return nil
}

func (x *Expression) GetComparison() *ComparisonExpr {
	if x != nil {
		if x, ok := x.Expr.(*Expression_Comparison); ok {
			return x.Comparison
		}
	}
	return nil
}

func (x *Expression) GetLogical() *LogicalExpr {
	if x != nil {
		if x, ok := x.Expr.(*Expression_Logical); ok {
			return x.Logical
		}
	}
	return nil
}

type isExpression_Expr interface {
	isExpression_Expr()
}

type Expression_Comparison struct {
	Comparison *ComparisonExpr `protobuf:"bytes,1,opt,name=comparison,proto3,oneof"`
}

type Expression_Logical struct {
	Logical *LogicalExpr `protobuf:"bytes,2,opt,name=logical,proto3,oneof"`
}

func (*Expression_Comparison) isExpression_Expr() {}

func (*Expression_Logical) isExpression_Expr() {}

type RangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Op            RangeOp                `protobuf:"varint,1,opt,name=op,proto3,enum=rangeservice.RangeOp" json:"op,omitempty"`
	TableId       uint32                 `protobuf:"varint,2,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	StartKey      uint64                 `protobuf:"varint,3,opt,name=start_key,json=startKey,proto3" json:"start_key,omitempty"`
	EndKey        uint64                 `protobuf:"varint,4,opt,name=end_key,json=endKey,proto3" json:"end_key,omitempty"`
	Key           uint64                 `protobuf:"varint,5,opt,name=key,proto3" json:"key,omitempty"`                              // INSERT: exact row key
	Fields        []*Field               `protobuf:"bytes,6,rep,name=fields,proto3" json:"fields,omitempty"`                         // INSERT: row data; UPDATE: new value
	Where         *Expression            `protobuf:"bytes,7,opt,name=where,proto3" json:"where,omitempty"`                           // SELECT/UPDATE/DELETE filter
	Columns       []int32                `protobuf:"varint,8,rep,packed,name=columns,proto3" json:"columns,omitempty"`               // SELECT: projection indices
	UpdateCol     int32                  `protobuf:"varint,9,opt,name=update_col,json=updateCol,proto3" json:"update_col,omitempty"` // UPDATE: column index to set
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RangeRequest) Reset() {
	*x = RangeRequest{}
	mi := &file_proto_rangeservice_range_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeRequest) ProtoMessage() {}

func (x *RangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rangeservice_range_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeRequest.ProtoReflect.Descriptor instead.
func (*RangeRequest) Descriptor() ([]byte, []int) {
	return file_proto_rangeservice_range_proto_rawDescGZIP(), []int{5}
}

func (x *RangeRequest) GetOp() RangeOp {
	if x != nil {
		return x.Op
	}
	return RangeOp_SCAN
}

func (x *RangeRequest) GetTableId() uint32 {
	if x != nil {
		return x.TableId
	}
	return 0
}

func (x *RangeRequest) GetStartKey() uint64 {
	if x != nil {
		return x.StartKey
	}
	return 0
}

func (x *RangeRequest) GetEndKey() uint64 {
	if x != nil {
		return x.EndKey
	}
	return 0
}

func (x *RangeRequest) GetKey() uint64 {
	if x != nil {
		return x.Key
	}
	return 0
}

func (x *RangeRequest) GetFields() []*Field {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *RangeRequest) GetWhere() *Expression {
	if x != nil {
		return x.Where
	}
	return nil
}

func (x *RangeRequest) GetColumns() []int32 {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *RangeRequest) GetUpdateCol() int32 {
	if x != nil {
		return x.UpdateCol
	}
	return 0
}

type ResultRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           uint64                 `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
	Fields        []*Field               `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultRow) Reset() {
	*x = ResultRow{}
	mi := &file_proto_rangeservice_range_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultRow) ProtoMessage() {}

func (x *ResultRow) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rangeservice_range_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultRow.ProtoReflect.Descriptor instead.
func (*ResultRow) Descriptor() ([]byte, []int) {
	return file_proto_rangeservice_range_proto_rawDescGZIP(), []int{6}
}

func (x *ResultRow) GetKey() uint64 {
	if x != nil {
		return x.Key
	}
	return 0
}

func (x *ResultRow) GetFields() []*Field {
	if x != nil {
		return x.Fields
	}
	return nil
}

type RangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          []*ResultRow           `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RangeResponse) Reset() {
	*x = RangeResponse{}
	mi := &file_proto_rangeservice_range_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeResponse) ProtoMessage() {}

func (x *RangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rangeservice_range_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeResponse.ProtoReflect.Descriptor instead.
func (*RangeResponse) Descriptor() ([]byte, []int) {
	return file_proto_rangeservice_range_proto_rawDescGZIP(), []int{7}
}

func (x *RangeResponse) GetRows() []*ResultRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *RangeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_rangeservice_range_proto protoreflect.FileDescriptor

const file_proto_rangeservice_range_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/rangeservice/range.proto\x12\frangeservice\"K\n" +
	"\n" +
	"FieldValue\x12\x19\n" +
	"\aint_val\x18\x01 \x01(\x03H\x00R\x06intVal\x12\x19\n" +
	"\astr_val\x18\x02 \x01(\tH\x00R\x06strValB\a\n" +
	"\x05value\"I\n" +
	"\x05Field\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\rR\x03tag\x12.\n" +
	"\x05value\x18\x02 \x01(\v2\x18.rangeservice.FieldValueR\x05value\"\x8c\x01\n" +
	"\x0eComparisonExpr\x12\x16\n" +
	"\x06column\x18\x01 \x01(\tR\x06column\x12\x1a\n" +
	"\boperator\x18\x02 \x01(\tR\boperator\x12#\n" +
	"\rliteral_value\x18\x03 \x01(\tR\fliteralValue\x12!\n" +
	"\fliteral_type\x18\x04 \x01(\x05R\vliteralType\"\x87\x01\n" +
	"\vLogicalExpr\x12\x1a\n" +
	"\boperator\x18\x01 \x01(\tR\boperator\x12,\n" +
	"\x04left\x18\x02 \x01(\v2\x18.rangeservice.ExpressionR\x04left\x12.\n" +
	"\x05right\x18\x03 \x01(\v2\x18.rangeservice.ExpressionR\x05right\"\x8b\x01\n" +
	"\n" +
	"Expression\x12>\n" +
	"\n" +
	"comparison\x18\x01 \x01(\v2\x1c.rangeservice.ComparisonExprH\x00R\n" +
	"comparison\x125\n" +
	"\alogical\x18\x02 \x01(\v2\x19.rangeservice.LogicalExprH\x00R\alogicalB\x06\n" +
	"\x04expr\"\xae\x02\n" +
	"\fRangeRequest\x12%\n" +
	"\x02op\x18\x01 \x01(\x0e2\x15.rangeservice.RangeOpR\x02op\x12\x19\n" +
	"\btable_id\x18\x02 \x01(\rR\atableId\x12\x1b\n" +
	"\tstart_key\x18\x03 \x01(\x04R\bstartKey\x12\x17\n" +
	"\aend_key\x18\x04 \x01(\x04R\x06endKey\x12\x10\n" +
	"\x03key\x18\x05 \x01(\x04R\x03key\x12+\n" +
	"\x06fields\x18\x06 \x03(\v2\x13.rangeservice.FieldR\x06fields\x12.\n" +
	"\x05where\x18\a \x01(\v2\x18.rangeservice.ExpressionR\x05where\x12\x18\n" +
	"\acolumns\x18\b \x03(\x05R\acolumns\x12\x1d\n" +
	"\n" +
	"update_col\x18\t \x01(\x05R\tupdateCol\"J\n" +
	"\tResultRow\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x12+\n" +
	"\x06fields\x18\x02 \x03(\v2\x13.rangeservice.FieldR\x06fields\"R\n" +
	"\rRangeResponse\x12+\n" +
	"\x04rows\x18\x01 \x03(\v2\x17.rangeservice.ResultRowR\x04rows\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error*7\n" +
	"\aRangeOp\x12\b\n" +
	"\x04SCAN\x10\x00\x12\n" +
	"\n" +
	"\x06INSERT\x10\x01\x12\n" +
	"\n" +
	"\x06UPDATE\x10\x02\x12\n" +
	"\n" +
	"\x06DELETE\x10\x032R\n" +
	"\fRangeService\x12B\n" +
	"\aExecute\x12\x1a.rangeservice.RangeRequest\x1a\x1b.rangeservice.RangeResponseBTZRgithub.com/your-username/DistributedDatabaseSystem/proto/rangeservice;rangeserviceb\x06proto3"

var (
	file_proto_rangeservice_range_proto_rawDescOnce sync.Once
	file_proto_rangeservice_range_proto_rawDescData []byte
)

func file_proto_rangeservice_range_proto_rawDescGZIP() []byte {
	file_proto_rangeservice_range_proto_rawDescOnce.Do(func() {
		file_proto_rangeservice_range_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_rangeservice_range_proto_rawDesc), len(file_proto_rangeservice_range_proto_rawDesc)))
	})
	return file_proto_rangeservice_range_proto_rawDescData
}

var file_proto_rangeservice_range_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_rangeservice_range_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_rangeservice_range_proto_goTypes = []any{
	(RangeOp)(0),           // 0: rangeservice.RangeOp
	(*FieldValue)(nil),     // 1: rangeservice.FieldValue
	(*Field)(nil),          // 2: rangeservice.Field
	(*ComparisonExpr)(nil), // 3: rangeservice.ComparisonExpr
	(*LogicalExpr)(nil),    // 4: rangeservice.LogicalExpr
	(*Expression)(nil),     // 5: rangeservice.Expression
	(*RangeRequest)(nil),   // 6: rangeservice.RangeRequest
	(*ResultRow)(nil),      // 7: rangeservice.ResultRow
	(*RangeResponse)(nil),  // 8: rangeservice.RangeResponse
}
var file_proto_rangeservice_range_proto_depIdxs = []int32{
	1,  // 0: rangeservice.Field.value:type_name -> rangeservice.FieldValue
	5,  // 1: rangeservice.LogicalExpr.left:type_name -> rangeservice.Expression
	5,  // 2: rangeservice.LogicalExpr.right:type_name -> rangeservice.Expression
	3,  // 3: rangeservice.Expression.comparison:type_name -> rangeservice.ComparisonExpr
	4,  // 4: rangeservice.Expression.logical:type_name -> rangeservice.LogicalExpr
	0,  // 5: rangeservice.RangeRequest.op:type_name -> rangeservice.RangeOp
	2,  // 6: rangeservice.RangeRequest.fields:type_name -> rangeservice.Field
	5,  // 7: rangeservice.RangeRequest.where:type_name -> rangeservice.Expression
	2,  // 8: rangeservice.ResultRow.fields:type_name -> rangeservice.Field
	7,  // 9: rangeservice.RangeResponse.rows:type_name -> rangeservice.ResultRow
	6,  // 10: rangeservice.RangeService.Execute:input_type -> rangeservice.RangeRequest
	8,  // 11: rangeservice.RangeService.Execute:output_type -> rangeservice.RangeResponse
	11, // [11:12] is the sub-list for method output_type
	10, // [10:11] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_rangeservice_range_proto_init() }
func file_proto_rangeservice_range_proto_init() {
	if File_proto_rangeservice_range_proto != nil {
		return
	}
	file_proto_rangeservice_range_proto_msgTypes[0].OneofWrappers = []any{
		(*FieldValue_IntVal)(nil),
		(*FieldValue_StrVal)(nil),
	}
	file_proto_rangeservice_range_proto_msgTypes[4].OneofWrappers = []any{
		(*Expression_Comparison)(nil),
		(*Expression_Logical)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_rangeservice_range_proto_rawDesc), len(file_proto_rangeservice_range_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_rangeservice_range_proto_goTypes,
		DependencyIndexes: file_proto_rangeservice_range_proto_depIdxs,
		EnumInfos:         file_proto_rangeservice_range_proto_enumTypes,
		MessageInfos:      file_proto_rangeservice_range_proto_msgTypes,
	}.Build()
	File_proto_rangeservice_range_proto = out.File
	file_proto_rangeservice_range_proto_goTypes = nil
	file_proto_rangeservice_range_proto_depIdxs = nil
}
