// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/repl/repl.proto

package replication

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FieldList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ElemType      uint32                 `protobuf:"varint,1,opt,name=elem_type,json=elemType,proto3" json:"elem_type,omitempty"`
	Elems         []*FieldValue          `protobuf:"bytes,2,rep,name=elems,proto3" json:"elems,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldList) Reset() {
	*x = FieldList{}
	mi := &file_proto_repl_repl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldList) ProtoMessage() {}

func (x *FieldList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_repl_repl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldList.ProtoReflect.Descriptor instead.
func (*FieldList) Descriptor() ([]byte, []int) {
	return file_proto_repl_repl_proto_rawDescGZIP(), []int{0}
}

func (x *FieldList) GetElemType() uint32 {
	if x != nil {
		return x.ElemType
	}
	return 0
}

func (x *FieldList) GetElems() []*FieldValue {
	if x != nil {
		return x.Elems
	}
	return nil
}

type FieldValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*FieldValue_IntValue
	//	*FieldValue_StringValue
	//	*FieldValue_BoolValue
	//	*FieldValue_ListValue
	Value         isFieldValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldValue) Reset() {
	*x = FieldValue{}
	mi := &file_proto_repl_repl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldValue) ProtoMessage() {}

func (x *FieldValue) ProtoReflect() protoreflect.Message {
	mi := &file_proto_repl_repl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldValue.ProtoReflect.Descriptor instead.
func (*FieldValue) Descriptor() ([]byte, []int) {
	return file_proto_repl_repl_proto_rawDescGZIP(), []int{1}
}

func (x *FieldValue) GetValue() isFieldValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *FieldValue) GetIntValue() int64 {
	if x != nil {
		if x, ok := x.Value.(*FieldValue_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *FieldValue) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*FieldValue_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *FieldValue) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*FieldValue_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *FieldValue) GetListValue() *FieldList {
	if x != nil {
		if x, ok := x.Value.(*FieldValue_ListValue); ok {
			return x.ListValue
		}
	}
	return nil
}

type isFieldValue_Value interface {
	isFieldValue_Value()
}

type FieldValue_IntValue struct {
	IntValue int64 `protobuf:"varint,1,opt,name=int_value,json=intValue,proto3,oneof"`
}

type FieldValue_StringValue struct {
	StringValue string `protobuf:"bytes,2,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type FieldValue_BoolValue struct {
	BoolValue bool `protobuf:"varint,3,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type FieldValue_ListValue struct {
	ListValue *FieldList `protobuf:"bytes,4,opt,name=list_value,json=listValue,proto3,oneof"`
}

func (*FieldValue_IntValue) isFieldValue_Value() {}

func (*FieldValue_StringValue) isFieldValue_Value() {}

func (*FieldValue_BoolValue) isFieldValue_Value() {}

func (*FieldValue_ListValue) isFieldValue_Value() {}

type ReplicationLogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lsn           uint64                 `protobuf:"varint,1,opt,name=lsn,proto3" json:"lsn,omitempty"`
	Op            int32                  `protobuf:"varint,2,opt,name=op,proto3" json:"op,omitempty"`
	Key           uint64                 `protobuf:"varint,3,opt,name=key,proto3" json:"key,omitempty"`
	Fields        []*FieldValue          `protobuf:"bytes,4,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicationLogEntry) Reset() {
	*x = ReplicationLogEntry{}
	mi := &file_proto_repl_repl_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicationLogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicationLogEntry) ProtoMessage() {}

func (x *ReplicationLogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_repl_repl_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicationLogEntry.ProtoReflect.Descriptor instead.
func (*ReplicationLogEntry) Descriptor() ([]byte, []int) {
	return file_proto_repl_repl_proto_rawDescGZIP(), []int{2}
}

func (x *ReplicationLogEntry) GetLsn() uint64 {
	if x != nil {
		return x.Lsn
	}
	return 0
}

func (x *ReplicationLogEntry) GetOp() int32 {
	if x != nil {
		return x.Op
	}
	return 0
}

func (x *ReplicationLogEntry) GetKey() uint64 {
	if x != nil {
		return x.Key
	}
	return 0
}

func (x *ReplicationLogEntry) GetFields() []*FieldValue {
	if x != nil {
		return x.Fields
	}
	return nil
}

type PullRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartLsn      uint64                 `protobuf:"varint,1,opt,name=start_lsn,json=startLsn,proto3" json:"start_lsn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullRequest) Reset() {
	*x = PullRequest{}
	mi := &file_proto_repl_repl_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullRequest) ProtoMessage() {}

func (x *PullRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_repl_repl_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullRequest.ProtoReflect.Descriptor instead.
func (*PullRequest) Descriptor() ([]byte, []int) {
	return file_proto_repl_repl_proto_rawDescGZIP(), []int{3}
}

func (x *PullRequest) GetStartLsn() uint64 {
	if x != nil {
		return x.StartLsn
	}
	return 0
}

type PullResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*ReplicationLogEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullResponse) Reset() {
	*x = PullResponse{}
	mi := &file_proto_repl_repl_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullResponse) ProtoMessage() {}

func (x *PullResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_repl_repl_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullResponse.ProtoReflect.Descriptor instead.
func (*PullResponse) Descriptor() ([]byte, []int) {
	return file_proto_repl_repl_proto_rawDescGZIP(), []int{4}
}

func (x *PullResponse) GetEntries() []*ReplicationLogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_proto_repl_repl_proto protoreflect.FileDescriptor

const file_proto_repl_repl_proto_rawDesc = "" +
	"\n" +
	"\x15proto/repl/repl.proto\x12\vreplication\"W\n" +
	"\tFieldList\x12\x1b\n" +
	"\telem_type\x18\x01 \x01(\rR\belemType\x12-\n" +
	"\x05elems\x18\x02 \x03(\v2\x17.replication.FieldValueR\x05elems\"\xb3\x01\n" +
	"\n" +
	"FieldValue\x12\x1d\n" +
	"\tint_value\x18\x01 \x01(\x03H\x00R\bintValue\x12#\n" +
	"\fstring_value\x18\x02 \x01(\tH\x00R\vstringValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x03 \x01(\bH\x00R\tboolValue\x127\n" +
	"\n" +
	"list_value\x18\x04 \x01(\v2\x16.replication.FieldListH\x00R\tlistValueB\a\n" +
	"\x05value\"z\n" +
	"\x13ReplicationLogEntry\x12\x10\n" +
	"\x03lsn\x18\x01 \x01(\x04R\x03lsn\x12\x0e\n" +
	"\x02op\x18\x02 \x01(\x05R\x02op\x12\x10\n" +
	"\x03key\x18\x03 \x01(\x04R\x03key\x12/\n" +
	"\x06fields\x18\x04 \x03(\v2\x17.replication.FieldValueR\x06fields\"*\n" +
	"\vPullRequest\x12\x1b\n" +
	"\tstart_lsn\x18\x01 \x01(\x04R\bstartLsn\"J\n" +
	"\fPullResponse\x12:\n" +
	"\aentries\x18\x01 \x03(\v2 .replication.ReplicationLogEntryR\aentries2\\\n" +
	"\x12ReplicationService\x12F\n" +
	"\rStreamUpdates\x12\x18.replication.PullRequest\x1a\x19.replication.PullResponse0\x01BFZDgithub.com/your-username/DistributedDatabaseSystem/proto/replicationb\x06proto3"

var (
	file_proto_repl_repl_proto_rawDescOnce sync.Once
	file_proto_repl_repl_proto_rawDescData []byte
)

func file_proto_repl_repl_proto_rawDescGZIP() []byte {
	file_proto_repl_repl_proto_rawDescOnce.Do(func() {
		file_proto_repl_repl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_repl_repl_proto_rawDesc), len(file_proto_repl_repl_proto_rawDesc)))
	})
	return file_proto_repl_repl_proto_rawDescData
}

var file_proto_repl_repl_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_repl_repl_proto_goTypes = []any{
	(*FieldList)(nil),           // 0: replication.FieldList
	(*FieldValue)(nil),          // 1: replication.FieldValue
	(*ReplicationLogEntry)(nil), // 2: replication.ReplicationLogEntry
	(*PullRequest)(nil),         // 3: replication.PullRequest
	(*PullResponse)(nil),        // 4: replication.PullResponse
}
var file_proto_repl_repl_proto_depIdxs = []int32{
	1, // 0: replication.FieldList.elems:type_name -> replication.FieldValue
	0, // 1: replication.FieldValue.list_value:type_name -> replication.FieldList
	1, // 2: replication.ReplicationLogEntry.fields:type_name -> replication.FieldValue
	2, // 3: replication.PullResponse.entries:type_name -> replication.ReplicationLogEntry
	3, // 4: replication.ReplicationService.StreamUpdates:input_type -> replication.PullRequest
	4, // 5: replication.ReplicationService.StreamUpdates:output_type -> replication.PullResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_repl_repl_proto_init() }
func file_proto_repl_repl_proto_init() {
	if File_proto_repl_repl_proto != nil {
		return
	}
	file_proto_repl_repl_proto_msgTypes[1].OneofWrappers = []any{
		(*FieldValue_IntValue)(nil),
		(*FieldValue_StringValue)(nil),
		(*FieldValue_BoolValue)(nil),
		(*FieldValue_ListValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_repl_repl_proto_rawDesc), len(file_proto_repl_repl_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_repl_repl_proto_goTypes,
		DependencyIndexes: file_proto_repl_repl_proto_depIdxs,
		MessageInfos:      file_proto_repl_repl_proto_msgTypes,
	}.Build()
	File_proto_repl_repl_proto = out.File
	file_proto_repl_repl_proto_goTypes = nil
	file_proto_repl_repl_proto_depIdxs = nil
}
