// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/db/db.proto

package db

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SQLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sql           string                 `protobuf:"bytes,1,opt,name=sql,proto3" json:"sql,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SQLRequest) Reset() {
	*x = SQLRequest{}
	mi := &file_proto_db_db_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SQLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SQLRequest) ProtoMessage() {}

func (x *SQLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_db_db_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SQLRequest.ProtoReflect.Descriptor instead.
func (*SQLRequest) Descriptor() ([]byte, []int) {
	return file_proto_db_db_proto_rawDescGZIP(), []int{0}
}

func (x *SQLRequest) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

type SQLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Columns       []string               `protobuf:"bytes,1,rep,name=columns,proto3" json:"columns,omitempty"`
	Rows          []*ResultRow           `protobuf:"bytes,2,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SQLResponse) Reset() {
	*x = SQLResponse{}
	mi := &file_proto_db_db_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SQLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SQLResponse) ProtoMessage() {}

func (x *SQLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_db_db_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SQLResponse.ProtoReflect.Descriptor instead.
func (*SQLResponse) Descriptor() ([]byte, []int) {
	return file_proto_db_db_proto_rawDescGZIP(), []int{1}
}

func (x *SQLResponse) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *SQLResponse) GetRows() []*ResultRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

type ResultRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        []*FieldValue          `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultRow) Reset() {
	*x = ResultRow{}
	mi := &file_proto_db_db_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultRow) ProtoMessage() {}

func (x *ResultRow) ProtoReflect() protoreflect.Message {
	mi := &file_proto_db_db_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultRow.ProtoReflect.Descriptor instead.
func (*ResultRow) Descriptor() ([]byte, []int) {
	return file_proto_db_db_proto_rawDescGZIP(), []int{2}
}

func (x *ResultRow) GetFields() []*FieldValue {
	if x != nil {
		return x.Fields
	}
	return nil
}

type FieldValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*FieldValue_IntValue
	//	*FieldValue_StringValue
	//	*FieldValue_BoolValue
	Value         isFieldValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldValue) Reset() {
	*x = FieldValue{}
	mi := &file_proto_db_db_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldValue) ProtoMessage() {}

func (x *FieldValue) ProtoReflect() protoreflect.Message {
	mi := &file_proto_db_db_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldValue.ProtoReflect.Descriptor instead.
func (*FieldValue) Descriptor() ([]byte, []int) {
	return file_proto_db_db_proto_rawDescGZIP(), []int{3}
}

func (x *FieldValue) GetValue() isFieldValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *FieldValue) GetIntValue() int64 {
	if x != nil {
		if x, ok := x.Value.(*FieldValue_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *FieldValue) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*FieldValue_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *FieldValue) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*FieldValue_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

type isFieldValue_Value interface {
	isFieldValue_Value()
}

type FieldValue_IntValue struct {
	IntValue int64 `protobuf:"varint,1,opt,name=int_value,json=intValue,proto3,oneof"`
}

type FieldValue_StringValue struct {
	StringValue string `protobuf:"bytes,2,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type FieldValue_BoolValue struct {
	BoolValue bool `protobuf:"varint,3,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

func (*FieldValue_IntValue) isFieldValue_Value() {}

func (*FieldValue_StringValue) isFieldValue_Value() {}

func (*FieldValue_BoolValue) isFieldValue_Value() {}

var File_proto_db_db_proto protoreflect.FileDescriptor

const file_proto_db_db_proto_rawDesc = "" +
	"\n" +
	"\x11proto/db/db.proto\x12\adbproto\"\x1e\n" +
	"\n" +
	"SQLRequest\x12\x10\n" +
	"\x03sql\x18\x01 \x01(\tR\x03sql\"O\n" +
	"\vSQLResponse\x12\x18\n" +
	"\acolumns\x18\x01 \x03(\tR\acolumns\x12&\n" +
	"\x04rows\x18\x02 \x03(\v2\x12.dbproto.ResultRowR\x04rows\"8\n" +
	"\tResultRow\x12+\n" +
	"\x06fields\x18\x01 \x03(\v2\x13.dbproto.FieldValueR\x06fields\"z\n" +
	"\n" +
	"FieldValue\x12\x1d\n" +
	"\tint_value\x18\x01 \x01(\x03H\x00R\bintValue\x12#\n" +
	"\fstring_value\x18\x02 \x01(\tH\x00R\vstringValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x03 \x01(\bH\x00R\tboolValueB\a\n" +
	"\x05value2B\n" +
	"\n" +
	"SQLService\x124\n" +
	"\aExecute\x12\x13.dbproto.SQLRequest\x1a\x14.dbproto.SQLResponseB>Z<github.com/your-username/DistributedDatabaseSystem/pkg/db;dbb\x06proto3"

var (
	file_proto_db_db_proto_rawDescOnce sync.Once
	file_proto_db_db_proto_rawDescData []byte
)

func file_proto_db_db_proto_rawDescGZIP() []byte {
	file_proto_db_db_proto_rawDescOnce.Do(func() {
		file_proto_db_db_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_db_db_proto_rawDesc), len(file_proto_db_db_proto_rawDesc)))
	})
	return file_proto_db_db_proto_rawDescData
}

var file_proto_db_db_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_db_db_proto_goTypes = []any{
	(*SQLRequest)(nil),  // 0: dbproto.SQLRequest
	(*SQLResponse)(nil), // 1: dbproto.SQLResponse
	(*ResultRow)(nil),   // 2: dbproto.ResultRow
	(*FieldValue)(nil),  // 3: dbproto.FieldValue
}
var file_proto_db_db_proto_depIdxs = []int32{
	2, // 0: dbproto.SQLResponse.rows:type_name -> dbproto.ResultRow
	3, // 1: dbproto.ResultRow.fields:type_name -> dbproto.FieldValue
	0, // 2: dbproto.SQLService.Execute:input_type -> dbproto.SQLRequest
	1, // 3: dbproto.SQLService.Execute:output_type -> dbproto.SQLResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_db_db_proto_init() }
func file_proto_db_db_proto_init() {
	if File_proto_db_db_proto != nil {
		return
	}
	file_proto_db_db_proto_msgTypes[3].OneofWrappers = []any{
		(*FieldValue_IntValue)(nil),
		(*FieldValue_StringValue)(nil),
		(*FieldValue_BoolValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_db_db_proto_rawDesc), len(file_proto_db_db_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_db_db_proto_goTypes,
		DependencyIndexes: file_proto_db_db_proto_depIdxs,
		MessageInfos:      file_proto_db_db_proto_msgTypes,
	}.Build()
	File_proto_db_db_proto = out.File
	file_proto_db_db_proto_goTypes = nil
	file_proto_db_db_proto_depIdxs = nil
}
